---
- name: "Create {{ flux_user }} user"
  block:
    - name: Create a new user with the given name
      user: 
        name: "{{ flux_user }}"
        comment: "{{ item.comment }}"
        state: "{{ item.state }}"
        groups: "{{ item.groups }}"
        append: yes
        shell: /bin/bash
        createhome: yes
      loop:
        - name: "{{ flux_user }}"
          comment: "User for flux node config"
          groups: "sudo"
          state: "present"
    
    - name: "Create {{ flux_user }} sudoers file"
      file:
        path: "/etc/sudoers.d/{{ flux_user }}"
        state: touch

    - name: "Grant {{ flux_user }} passwordless sudo"
      lineinfile:
        dest: /etc/sudoers.d/techdufus
        state: present
        line: "{{ flux_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"

    - name: "Create ~/.ssh directory for {{ flux_user }}"
      file:
        path: "/home/{{ flux_user }}/.ssh"
        state: directory
        owner: "{{ flux_user }}"
        group: "{{ flux_user }}"


    - name: Copy root user's authorized_keys to the new user's home directory
      file:
        path: /home/{{ flux_user }}/.ssh/authorized_keys
        owner: "{{ flux_user }}"
        group: "{{ flux_user }}"
        state: touch

    - name: "Set {{ flux_user }}'s authorized_keys"
      shell: cat /root/.ssh/authorized_keys > /home/{{ flux_user }}/.ssh/authorized_keys
