---
- name: Update APT packages
  apt:
    update_cache: yes

- name: Upgrade APT packages
  apt:
    upgrade: 'yes' # <-- This expects a STRING for some reason...
  
- name: Install APT packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ commonPackages }}"

- name: Deploy update alias
  copy:
    src: "update_alias.sh"
    dest: /etc/profile.d/update_alias.sh
    force: yes
  become: yes

- name: Install Nala
  block:
    - name: Add nala repo gpg key
      apt_key:
        url: "https://deb.volian.org/volian/scar.key"
        state: present

    - name: Add nala repository source
      apt_repository:
        repo: "deb https://deb.volian.org/volian/ scar main"
        state: present

    - name: Install Nala
      apt:
        name: nala
        state: latest
      when: ansible_distribution_major_version == "22"

    - name: Install Nala-legacy
      apt:
        name: nala-legacy
        state: latest
        update_cache: yes
      when: ansible_distribution_major_version == "20"

- name: Add distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yaml"

- import_tasks: unattended-upgrades.yaml
  tags: unattended-upgrades

- name: Check for pending reboot
  shell: |
    if [ -f /var/run/reboot-required ]; then
      echo "1"
    else
      echo "0"
    fi
  register: reboot_required
  changed_when: false

- name: REBOOT REQUIRED - IF THIS IS YELLOW THIS NODE NEEDS TO REBOOT
  shell: echo "This needs to reboot"
  when: reboot_required.stdout|bool 

- name: "*** --- ___REBOOTING SERVERS___ --- ***"
  reboot:
  throttle: 1
  when: 
    - reboot_required.stdout|bool
    - inventory_hostname not in groups.fluxnodes
    - inventory_hostname not in groups.vpnhost
