apiVersion: v1
kind: Service
metadata:
  name: argocd-tailscale
  namespace: argocd
  annotations:
    tailscale.com/hostname: "argocd"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: argocd-server
