# NFS CSI Driver - Homelab Configuration
storageClass:
  create: true
  name: nfs-shared
  parameters:
    server: "10.0.0.254"
    share: "/var/nfs/shared/Homelab"
    mountPermissions: "0775"
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  mountOptions:
    - nfsvers=3
    - hard
