apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-database
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # Ignore CNPG webhook defaults that cause drift
  # CNPG admission webhook sets many default values not in our manifest
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jqPathExpressions:
        # Ignore entire spec except fields we explicitly set
        - .spec.affinity
        - .spec.enablePDB
        - .spec.enableSuperuserAccess
        - .spec.failoverDelay
        - .spec.logLevel
        - .spec.maxSyncReplicas
        - .spec.minSyncReplicas
        - .spec.monitoring
        - .spec.postgresGID
        - .spec.postgresUID
        - .spec.primaryUpdateMethod
        - .spec.primaryUpdateStrategy
        - .spec.replicationSlots
        - .spec.smartShutdownTimeout
        - .spec.startDelay
        - .spec.stopDelay
        - .spec.switchoverDelay
        # Ignore entire postgresql section - CNPG heavily modifies it
        - .spec.postgresql
        # Resources and storage have normalization and defaults
        - .spec.resources
        - .spec.storage
  source:
    repoURL: https://github.com/TechDufus/home.io
    targetRevision: main
    path: kubernetes/argocd/manifests/immich-database
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 10s  # Longer delay for database initialization
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10  # Infrastructure component